name = "main"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Eric Perlade"]
maintainers = ["Eric Perlade <perlade@adacore.com>"]
maintainers-logins = ["noname"]

executables = ["main"]
[[depends-on]]
gnatprove = "^12.1.1"
