version: "3.9"

services:
  nginx: 
    image: registry.zarak.fr/library/nginx:stable-alpine3.17-slim
    links:
      - frontend
      - backend
    ports:
      - 80:80
    volumes : 
      - /tmp/nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build: ./frontend
    links: 
      - backend

  backend: 
    build: ./backend
    links:
      - redis
    volumes:
      - /tmp/backend/:/cache/

  redis:
    image: registry.zarak.fr/library/redis:6-alpine
